import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "@/componnents/header/Header";

import { ToastContainer, Bounce } from 'react-toastify';
import { AuthProvider } from "../context/UserContext";
import Footer from "@/componnents/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Techsphere",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
        <Header />
        <ToastContainer pauseOnFocusLoss closeOnClick={true}  pauseOnHover transition={Bounce} theme='colored' />
        <main>
       

        {children}


        </main>
        <Footer />
       </AuthProvider>
      </body>
    </html>
  );
}
