import { Bounce, ToastContainer } from "react-toastify"
import { AuthProvider, } from "../context/UserContext"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <ToastContainer 
        pauseOnFocusLoss 
        closeOnClick 
        pauseOnHover 
        transition={Bounce} 
        theme='colored' 
      />
       <AuthProvider>
      <body>{children}</body>

      </AuthProvider>
    </html>
  )
}
